sudo: required

language: generic 

services:
  - docker

before_install:
  - docker build -t lcruz0709/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lcruz0709/docker-react npm run test -- --coverage
